const ACTIONS = {
  MESSAGE : {
    SHOW :  "SHOW" ,
    HIDE_AND_REMOVE : "HIDE_AND_REMOVE"
  },
  AUTH : {
    LOG_IN : "LOG_IN_LOCALLY",
    LOG_OUT : "LOG_OUT",
    SET_FETCHING_USER : "SET_FETCHING_USER",
    CLEAR_USER : "CLEAR_USER",
  },
  SHIPMENTS: {
    SET_ALL: 'SHIPMENTS/SET_ALL',
    SET_STATUSES: 'SHIPMENTS/SET_STATUSES',
    ADD: 'SHIPMENTS/ADD',
    UPDATE: 'SHIPMENTS/UPDATE',
    REMOVE: 'SHIPMENTS/REMOVE',
    SET_LOADING: 'SHIPMENTS/SET_LOADING',
  },
  SUB_SHIPMENTS: {
    SET_DATA: 'SUB_SHIPMENTS/SET_DATA',
    SET_USER_DATA: 'SUB_SHIPMENTS/SET_USER_DATA',
    SET_FORM_DATA: 'SUB_SHIPMENTS/SET_FORM_DATA',
    SET_STATUSES: 'SUB_SHIPMENTS/SET_STATUSES',
    UPDATE: 'SUB_SHIPMENTS/UPDATE',
    UPDATE_PROOF: 'SUB_SHIPMENTS/UPDATE_PROOF',
    REMOVE: 'SUB_SHIPMENTS/REMOVE',
    CLEAR: 'SUB_SHIPMENTS/CLEAR',
    SET_LOADING: 'SUB_SHIPMENTS/SET_LOADING',
  },
  USERS: {
    SET_ALL: 'USERS/SET_ALL',
    ADD: 'USERS/ADD',
    UPDATE: 'USERS/UPDATE',
    REMOVE: 'USERS/REMOVE',
  },
  COUNTRIES: {
    SET_ALL: 'COUNTRIES/SET_ALL',
    ADD: 'COUNTRIES/ADD',
    UPDATE: 'COUNTRIES/UPDATE',
    REMOVE: 'COUNTRIES/REMOVE',
  },
  ITEM_TYPES: {
    SET_ALL: 'ITEM_TYPES/SET_ALL',
    ADD: 'ITEM_TYPES/ADD',
    UPDATE: 'ITEM_TYPES/UPDATE',
    REMOVE: 'ITEM_TYPES/REMOVE',
  },
}

export default ACTIONS;
export const { MESSAGE : MESSAGE_ACTIONS, AUTH : AUTH_ACTIONS } = ACTIONS;